export const LOGIN_USER_FINISH = "LOGIN_USER_FINISH";

export const UPDATE_USER_MODE = "UPDATE_USER_MODE";

export const START_API_CALL = "START_API_CALL";

export const API_CALL_FAIL = "API_CALL_FAIL";

export const UPDATE_USER_DATA_FINISH = "UPDATE_USER_DATA_FINISH";

export const UPDATE_USER_STATUS_FINISH = "UPDATE_USER_STATUS_FINISH";

export const UPDATE_PASSWORD_FINISH = "UPDATE_PASSWORD_FINISH";

export const LOGOUT = "LOGOUT";
