export const FETCH_USERS_FINISH = "FETCH_USERS_FINISH";

export const START_API_CALL = "START_API_CALL";

export const API_CALL_FAIL = "API_CALL_FAIL";

export const UPDATE_ACTIVATION_USER_FINISH = "UPDATE_ACTIVATION_USER_FINISH";

export const UPDATE_USER_FINISH = "UPDATE_USER_FINISH";

export const ADD_NEW_USER_FINISH = "ADD_NEW_USER_FINISH";
