export const FETCH_COMMUNITIES_FINISH = "FETCH_COMMUNITIES_FINISH";

export const START_API_CALL = "START_API_CALL";

export const API_CALL_FAIL = "API_CALL_FAIL";

export const UPDATE_ACTIVATION_COMMUNITY_FINISH =
  "UPDATE_ACTIVATION_COMMUNITY_FINISH";

export const ADD_NEW_COMMUNITY_FINISH = "ADD_NEW_COMMUNITY_FINISH";
